d=Deck(10,'密度分群與機率模型','第 10 週｜DBSCAN、Gaussian Mixture、EM 與異常偵測','主教材 Ch.8 pp.265–282','05 s.12–27')
d.add('本週成果與三段安排','0–50 分：密度鄰域、DBSCAN 與其他分群方法。\n\n60–120 分：GMM、EM 與機率密度。\n\n130–180 分：異常偵測、AIC／BIC、模型比較。\n\n成果：能分清楚群機率、密度、異常分數與判定閾值。',weight=1)
d.add('DBSCAN：密集區域透過核心點連成一群',r'$\varepsilon$ 鄰域：距離不超過 eps 的所有點。'+'\n\n- 核心點：鄰域樣本數（包含自己）至少 `min_samples`。\n- 邊界點：不是核心，但位於某個核心點的鄰域。\n- 雜訊點：不是核心，且不在任何核心點的鄰域。','主教材 Ch.8 p.265；舊稿 05 s.24–27',note='群透過核心點鏈連接；不要用邊界點當橋把兩個群串起來。')
d.fig('8-13','改變 eps：同一資料會從破碎變成連續','eps 太小可能切出大量小群與雜訊；太大可能把原本分開的群合併。')
d.add('讀取 DBSCAN 結果','```python\nfrom sklearn.cluster import DBSCAN\ndb = DBSCAN(eps=0.2, min_samples=5).fit(X)\nlabels = db.labels_                 # -1 表示雜訊\ncore_indices = db.core_sample_indices_\ncore_points = db.components_\n```\n\n先決定距離與特徵尺度，再選 eps；不同尺度不能共用同一數值。','主教材 Ch.8 pp.265–266',cls='small')
d.activity('手算鄰域：誰是核心，誰是雜訊？','一維點 `[0, .1, .2, .4, 2.0]`，eps=.21、min_samples=3。\n\n1. 列出每點鄰域數（包含自己）。\n2. 判定核心、邊界與雜訊。\n3. 如果 min_samples 增加為 4，結果如何？','鄰域數 [3,3,4,2,1]；0,.1,.2為核心，.4邊界，2雜訊。改4後只有.2核心，0,.1,.4均在其鄰域為邊界，2仍雜訊。',weight=12)
d.add('DBSCAN 沒有原生 predict，延伸要另訂規則','`fit_predict` 是對參與分群的資料給群號。\n\n新點可用核心點訓練近鄰分類器，但那是額外的分類規則。\n\n只用近鄰會把很遠的點也分到某群；需要最大距離拒絕機制。','主教材 Ch.8 pp.266–267')
d.fig('8-14','新點的延伸分類：距離過遠應拒絕','圖中的分類邊界來自後加的近鄰模型，不是 DBSCAN 自己的 predict。')
d.table('密度與階層方法：結構假設不同',['方法','主要概念','限制'],[['DBSCAN','核心點連接、辨識雜訊','不同密度群可能難共用 eps'],['HDBSCAN','考慮多尺度密度結構','仍需設定與評估'],['Agglomerative','由小群逐步合併','連結方式與距離影響結果'],['BIRCH','壓縮群摘要形成樹','適合大資料，仍受維度影響']],'主教材 Ch.8 pp.267–268；舊稿 05 s.21–27')
d.add('階層式分群補充：連結方式決定合併順序','Single linkage：兩群最近點的距離，容易形成鏈狀。\n\nComplete linkage：兩群最遠點距離，偏向緊密群。\n\nAverage linkage：跨群點對距離的平均。\n\nWard：選增加群內平方誤差最少的合併，搭配歐氏幾何。','舊稿 05 s.21–23（補充）',note='樹狀圖高度是合併準則值；不同linkage的高度不一定可直接比較。',core=False)
d.table('其他分群方法：保留教材的完整概覽',['方法','做法','需注意'],[['Mean-shift','移動視窗到局部高密度位置','bandwidth影響大；大資料成本高'],['Affinity propagation','訊息交換選代表樣本','不先指定k，但仍有偏好等參數'],['Spectral clustering','相似圖降維後再分群','圖與相似度設定、樣本規模']],'主教材 Ch.8 pp.268–269',note='不把這些簡介當成熟练操作要求；六週版課後閱讀。',core=False)
d.br()
d.add('GMM：先選一個成分，再從該高斯分布取樣',r'$$P(z=j)=\pi_j,\qquad x\mid z=j\sim\mathcal N(\mu_j,\Sigma_j)$$'+'\n\n'+r'$$p(x)=\sum_{j=1}^k\pi_j\mathcal N(x\mid\mu_j,\Sigma_j),\quad\sum_j\pi_j=1$$'+'\n\n每個成分有權重、中心與共變異；群可以是不同方向、大小的橢圓。','主教材 Ch.8 pp.269–270；舊稿 05 s.12–18')
d.add('多變量高斯：平均與共變異各控制什麼？',r'$$\mathcal N(x\mid\mu,\Sigma)=\frac{\exp[-\tfrac12(x-\mu)^T\Sigma^{-1}(x-\mu)]}{(2\pi)^{n/2}|\Sigma|^{1/2}}$$'+'\n\n$\mu$ 控制中心；$\Sigma$ 控制各方向的寬度與相關性。\n\n完整共變異須可逆；實務加小的對角正則項避免退化。','主教材 Ch.8 pp.269–273；舊稿 05 s.12–20（公式補充）',note='共變異過小可使密度非常高，混合模型似然可能退化；reg_covar與適當模型容量很重要。',cls='small',core=False)
d.fig('8-15','GMM 同時給群邊界與密度等高線','橢圓形密度符合此合成資料；這是模型假設適合資料的例子。')
d.add('EM 的 E-step：每個成分分擔多少責任？',r'$$r_{ij}=P(z_i=j\mid x_i)=\frac{\pi_j\mathcal N(x_i\mid\mu_j,\Sigma_j)}{\sum_l\pi_l\mathcal N(x_i\mid\mu_l,\Sigma_l)}$$'+'\n\n每列責任值加總為 1；點可部分屬於多個成分，稱為軟指派。','主教材 Ch.8 pp.270–271；舊稿 05 s.18–20（展開公式）',note='E-step不是重新亂猜標籤；是依目前參數計算後驗責任值。')
d.add('EM 的 M-step：用責任值重新估計參數',r'$$N_j=\sum_i r_{ij},\quad\pi_j=\frac{N_j}{m},\quad\mu_j=\frac{\sum_i r_{ij}x_i}{N_j}$$'+'\n\n'+r'$$\Sigma_j=\frac1{N_j}\sum_i r_{ij}(x_i-\mu_j)(x_i-\mu_j)^T$$'+'\n\n高責任值的樣本對該成分影響較大；反覆 E、M 直到收斂。','主教材 Ch.8 pp.270–271；舊稿 05 s.18–20（展開公式）')
d.activity('手算軟指派與更新','E-step：兩成分權重皆 .5，某點的密度為 .2 與 .05；責任值各多少？\n\nM-step：資料 `[0,2]`，成分 A 的責任值 `[.8,.2]`。計算 $N_A$、新權重、平均與變異。','E：[.8,.2]。M：N=1、π=.5、μ=.4；變異=.8×.16+.2×2.56=.64。另一成分責任值[.2,.8]，平均1.6、變異.64。',weight=12)
d.add('收斂不等於找到全域最優','EM 可卡在不好的局部解；使用多次初始化並比較最終似然。\n\n```python\nfrom sklearn.mixture import GaussianMixture\ngm = GaussianMixture(n_components=3, n_init=10,\n                     covariance_type="full", random_state=42)\ngm.fit(X_train)\nprint(gm.converged_, gm.n_iter_)\n```','主教材 Ch.8 pp.270–271',note='沒有收斂時檢查max_iter、tol、尺度、初始值與退化共變異，不要忽略警告直接報結果。',cls='small')
d.table('限制共變異：容量與成本的折衷',['covariance_type','可表示的形狀','共變異參數數量'],[['full','每群任意橢圓','每群 $n(n+1)/2$'],['tied','所有群共用同一橢圓','全部共用 $n(n+1)/2$'],['diag','每群軸平行橢圓','每群 n'],['spherical','每群球形、大小可不同','每群 1']],'主教材 Ch.8 p.273',note='尚未加均值和混合權重参數。full成本較高，資料少時更可能不穩。')
d.fig('8-16','tied 與 spherical：限制形狀會改變結果','不同共變異假設讓模型更簡單；是否值得，要看擬合與驗證證據。')
d.br()
d.add('機率、密度與生成：三個 API 回答不同問題','- `predict_proba(X)`：每筆屬於各成分的後驗機率。\n- `score_samples(X)`：每筆的對數機率密度。\n- `sample(n)`：從學到的混合分布生成新樣本。\n\n密度可大於 1；區域機率需要對該區域積分，不能把密度當成單點機率。','主教材 Ch.8 pp.271–272',note='連續分布下精確單點的機率為0；高密度表示附近單位體積聚集較多機率。')
d.fig('8-17','低密度異常：先估分數，再選閾值','教材用第 2 百分位作閾值，約標出 2% 的訓練樣本；這不是偵測成功率。')
d.add('異常閾值如何決定？','```python\nlog_density = gm.score_samples(X_train)\nthreshold = np.percentile(log_density, 2)\nflag = gm.score_samples(X_new) < threshold\n```\n\n比例應由可接受誤報、漏報與可複核量決定；用有標註驗證資料校準更有依據。','主教材 Ch.8 pp.274–275',note='異常不一定是錯誤或詐欺；模型也可能因分布轉移把正常新族群評為低密度。',cls='small')
d.fig('8-18','Likelihood：固定資料，比較不同參數','機率密度是固定參數看 x；似然是固定已觀測 x 看參數，後者不必對參數積分為 1。')
d.add('最大似然與 MAP：從乘積改成對數和',r'$$\ell(\theta)=\sum_i\log p(x_i\mid\theta),\qquad\hat\theta_{\rm MLE}=\arg\max_\theta\ell(\theta)$$'+'\n\nMAP 再加入先驗：最大化 $\ell(\\theta)+\log p(\\theta)$。\n\n對數是單調的，最大化位置不變；也能避免許多小數連乘下溢。','主教材 Ch.8 pp.276–277',core=False)
d.add('AIC 與 BIC：擬合收益要付出複雜度代價',r'$$\operatorname{AIC}=2p-2\log\hat{\mathcal L},\qquad\operatorname{BIC}=p\log m-2\log\hat{\mathcal L}$$'+'\n\n$p$ 是自由參數數量，$m$ 是樣本數；同一資料與可比較模型之間越小越好。\n\n不要用 K-means 的 inertia 直接選橢圓 GMM。','主教材 Ch.8 p.275，式 8-2')
d.add('數例：比較兩個 GMM 的複雜度代價','同樣 $m=100$：A 有 $p=5,\ell=-100$；B 有 $p=8,\ell=-96$。\n\nAIC：A=210、B=208，偏好 B。\n\nBIC：A≈223.03、B≈228.84，偏好 A。\n\n準則可能不一致；BIC 在此對參數增加的懲罰更大。','主教材 Ch.8 p.275；教學自製數例',note='分數是相對選擇，不能稱作預測正確率。不要跨不同資料轉換與不同樣本集直接比。')
d.fig('8-19','同時搜尋成分數與共變異假設','圖例展示不同 k 的準則；真正比較時也可納入 covariance_type。')
d.add('Bayesian GMM：給成分上限，讓權重收縮','`BayesianGaussianMixture` 可使不必要成分的權重接近零。\n\n`n_components` 是上限；先驗、初始化與資料仍會影響有效成分數。\n\n它不保證自動找到唯一、真實的群數。','主教材 Ch.8 p.278')
d.fig('8-20','彎月資料：多個高斯也可能切出很多小橢圓','密度估計可以有用途，但得到八個成分不代表資料語義上有八群。')
d.table('異常與新穎偵測方法概覽',['方法','主要訊號','假設或注意'],[['EllipticEnvelope／Fast-MCD','穩健橢圓範圍','正常資料近單一高斯'],['Isolation Forest','較少分割即可隔離','適合比較稀有、容易隔離的點'],['LOF','相對鄰居的局部密度','新資料用途需正確模式'],['One-class SVM','學正常資料的邊界','縮放、核與超參數影響大']],'主教材 Ch.8 pp.279–280',note='新穎偵測通常假定訓練資料較乾淨；異常偵測不要求完全乾淨。LOF用novelty=True後只對新資料評估，勿混用訓練分數。')
d.add('用重建誤差找異常：接回上一週的 PCA',r'$$e_i=\frac1n\|x_i-\operatorname{inverse\_transform}(\operatorname{transform}(x_i))\|^2$$'+'\n\n在正常資料表示下難以重建的點，可能有較高誤差。\n\n先用訓練／驗證資料設定閾值；正常但罕見的樣本也可能被標出。','主教材 Ch.8 pp.280–281',note='重建誤差是另一種分數，不是GMM密度；若異常恰好落在保留的子空間，PCA也可能偵測不到。')
d.activity('選模工作單：形狀、機率與用途一起決定','A：兩條彎月且有少數孤立點。\nB：方向不同的橢圓群，需要每點的群機率。\nC：高維表格資料，要篩出待人工複核的少數樣本。\n\n各選一個起點、兩個超參數或假設檢查，以及一個失敗風險。','A先DBSCAN/HDBSCAN，查尺度eps密度；B GMM，查k/covariance；C可試IsolationForest等，查閾值、標註評估與分布轉移。不是唯一正解，要說出理由。',weight=11)
d.add('離堂檢核與作業','1. 邊界點可以把兩個核心群串成一群嗎？\n2. 責任值與機率密度有何差別？\n3. 設定 2% 閾值，是否代表能抓到 98% 異常？\n\n課後：Ch.8 練習 6–13；比較 K-means、DBSCAN 與 GMM 的失敗案例。',note='答案：不可透過非核心邊界點延伸；责任值是成分后验且每列和1，密度是單位体积量；完全不是，需真实标签评估。',weight=2)
d.finish()

d=Deck(11,'人工神經網路入門','第 11 週｜從 Perceptron 到 MLP，走完一次前向與反向傳播','主教材 Ch.9 pp.285–315','06 s.1–38')
d.add('本週成果與節奏','0–50 分：人工神經元、Perceptron、XOR 與 MLP。\n\n60–120 分：非線性、鏈式法則與反向傳播。\n\n130–180 分：迴歸／分類架構、訓練與調參。\n\n成果：能列出網路形狀、手算梯度，完成小型 MLP 比較。',weight=1)
d.fig('9-1','從生物神經元得到啟發','人工神經元是數學模型；樹突、細胞體與軸突提供概念類比，不等於完整腦科學模擬。')
d.fig('9-2','很多單元組合，形成更複雜的處理','連接方式與權重決定訊息如何傳遞；學習是根據資料調整這些參數。')
d.fig('9-3','人工神經元可組合簡單邏輯','AND、OR、NOT 等邏輯可由不同連接與閾值表達；先觀察輸入如何決定輸出。')
d.fig('9-4','TLU：加權和，加偏置，再套階躍函數','輸入可以是實數；使用階躍時，輸出仍是離散的 0/1 或 −1/+1。')
d.add('階躍函數與單層輸出',r'$$\operatorname{step}(z)=\begin{cases}0&z<0\\1&z\ge0\end{cases},\quad\operatorname{sgn}(z)=\begin{cases}-1&z<0\\0&z=0\\1&z>0\end{cases}$$'+'\n\n'+r'$f(X)=\phi(XW+b)$。'+'\n\n$X:m\\times n$，$W:n\\times q$，$b:q$；偏置廣播到每列，輸出為 $m\\times q$。','主教材 Ch.9 pp.291–292，式 9-1、9-2',note='另一常見階躍符號用-1/+1；必須與目標編碼和更新規則一致。')
d.fig('9-5','Perceptron 層：每個輸出都看所有輸入','全連接層有一組輸入到輸出的權重；偏置可視為固定輸入 1 的連接。')
d.add('Perceptron 學習規則：答錯才修正',r'$$w_{i,j}\leftarrow w_{i,j}+\eta(y_j-\hat y_j)x_i$$'+'\n\n偏置同樣更新，等價令對應輸入為 1。線性可分資料可收斂到分隔面，但不保證最大間隔，也不直接輸出機率。','主教材 Ch.9 p.293，式 9-3；舊稿 06 s.6–9')
d.fig('9-6','XOR：一條線不夠，但組合多個單元可以','相同輸入位元輸出 0；不同輸出 1。隱藏層先建立中間邏輯特徵。')
d.table('XOR 真值表：把每一列實際走過網路',['A','B','A OR B','A AND B','XOR'],[['0','0','0','0','0'],['0','1','1','0','1'],['1','0','1','0','1'],['1','1','1','1','0']],'主教材 Ch.9 pp.294–295；舊稿 06 s.10–12',note='XOR=(A OR B) AND NOT(A AND B)。教材網路兩個隱藏節點可分別表示AND與OR，再做抑制組合。')
d.activity('手算 XOR 網路的四組輸入',r'$h_1=\operatorname{step}(A+B-1.5)$，$h_2=\operatorname{step}(A+B-.5)$。'+'\n\n'+r'$\hat y=\operatorname{step}(-h_1+h_2-.5)$。'+'\n\n代入四組輸入，確認輸出與真值表一致。再說明隱藏層增加了什麼能力。','00：h=[0,0]→0；01/10：[0,1]→1；11：[1,1]→0。隱藏層非線性組合把不可線性分的原始問題轉成可分表示。',weight=11)
d.fig('9-7','MLP：輸入、隱藏層與輸出層','前饋網路的訊號向前流動；每層產生下一層的特徵表示。')
d.br()
d.add('沒有非線性，堆再多層也會折成一層',r'$$f(g(x))=(xW_1+b_1)W_2+b_2=x(W_1W_2)+(b_1W_2+b_2)$$'+'\n\n因此需要非線性激活函數，才能讓深度帶來新的表達能力。','主教材 Ch.9 p.299；舊稿 06 s.22')
d.fig('9-8','Sigmoid、tanh、ReLU 與它們的導數','Sigmoid／tanh 的飽和區梯度很小；ReLU 的負半軸梯度為零。')
d.add('激活函數：用公式連結曲線與梯度',r'$$\sigma(z)=\frac1{1+e^{-z}},\quad\sigma\prime(z)=\sigma(z)(1-\sigma(z))$$'+'\n\n'+r'$$\tanh\prime(z)=1-\tanh^2(z),\quad\operatorname{ReLU}(z)=\max(0,z)$$'+'\n\nReLU 在 $z>0$ 導數為 1，$z<0$ 為 0；零點採實作約定。','主教材 Ch.9 pp.298–299；舊稿 06 s.23–24',note='可微不是說所有點都必須嚴格可微；ReLU在零點可使用次梯度約定。')
d.add('一次訓練步驟要分清楚四件事','1. 前向：計算各層輸出，保存中間值。\n2. 損失：比較預測與真值。\n3. 反向：用鏈式法則計算每個參數的梯度。\n4. 更新：optimizer 根據梯度調整參數。','主教材 Ch.9 pp.296–298；舊稿 06 s.14–20',note='教材有時用backprop廣義指整個訓練過程；本課狹義指反向算梯度，並把參數更新分開，以免把backprop等同GD。')
d.add('鏈式法則：沿路相乘，分支相加',r'$$\frac{\partial L}{\partial w}=\frac{\partial L}{\partial a}\frac{\partial a}{\partial z}\frac{\partial z}{\partial w}$$'+'\n\n$z=wx+b$、$a=\sigma(z)$。先計算靠近損失的梯度，再往前傳。\n\n一個參數若影響多條路徑，將各路徑貢獻相加。','主教材 Ch.9 pp.297–298；舊稿 06 s.14–20（推導補充）')
d.add('手算範例：一個 Sigmoid 神經元',r'$x=2,w=.5,b=0,y=1$，$L=\frac12(a-y)^2$。'+'\n\n'+r'$$z=1,\quad a=\sigma(1)\approx.731059,\quad L\approx.036165$$'+'\n\n'+r'$$\frac{\partial L}{\partial z}=(a-y)a(1-a)\approx-.052877$$','教學自製數例；舊稿 06 s.14–20',note='使用平方損失是為手算鏈式法則；正式分類通常用交叉熵。',core=True)
d.activity('接續手算：把梯度傳給權重與偏置',r'沿用 $\partial L/\partial z\approx-.052877$、$x=2$。'+'\n\n1. 求 $\partial L/\partial w$、$\partial L/\partial b$。\n2. 用學習率 0.1 更新 $w,b$。\n3. 重算預測，判斷損失是否下降。','dw=-.105754，db=-.052877；w=.5105754，b=.0052877；新z≈1.0264385，a≈.736225，L≈.034789。梯度不是新參數，須另做更新。',weight=13)
d.add('多層網路的形狀與反向遞迴',r'$$Z^{(l)}=A^{(l-1)}W^{(l)}+b^{(l)},\quad A^{(l)}=\phi_l(Z^{(l)})$$'+'\n\n'+r'$$\delta^{(l)}=(\delta^{(l+1)}W^{(l+1)T})\odot\phi_l\prime(Z^{(l)})$$'+'\n\n'+r'$$\nabla_{W^{(l)}}L=A^{(l-1)T}\delta^{(l)}$$'+'\n\n本頁 $\delta$ 定義為平均損失對 Z 的梯度，已包含批次平均因子。','主教材 Ch.9 pp.297–298；舊稿 06 s.14–20（矩陣補充）',note='偏置梯度為沿樣本軸加總δ。若δ定義為未平均逐樣本梯度，權重梯度須再除m，兩種寫法不能重複除。',cls='small',core=False)
d.add('初始化：打破隱藏神經元的對稱','同層神經元若具有完全一樣的權重與偏置，收到相同梯度後仍會一樣。\n\n隨機初始化權重讓它們學不同表示；偏置常可設為 0。\n\n多層小導數相乘會讓梯度消失；初始化尺度、激活與網路深度需一起考慮。','主教材 Ch.9 pp.298–299；舊稿 06 s.21、25')
d.br()
d.table('表 9-1：迴歸 MLP 的典型架構（1/2）',['項目','教材典型值'],[['隱藏層數','依問題，常見 1–5'],['每隱藏層神經元','依問題，常見 10–100'],['輸出神經元','每個目標維度 1 個'],['隱藏層激活','ReLU']],'主教材 Ch.9 p.303，表 9-1（上）',note='範圍只是入門參考，不是最佳架構規則。')
d.table('表 9-1：輸出範圍與損失（2/2）',['需求','輸出激活／損失'],[['任意實數','線性輸出'],['非負／正值','ReLU／softplus'],['有界範圍','Sigmoid／tanh，配合目標縮放'],['迴歸損失','MSE；有離群值可考慮 Huber']],'主教材 Ch.9 pp.302–303，表 9-1（下）',note='這是一般網路設計。MLPRegressor不能任意指定輸出激活或Huber；不能把表中的每個選項都當成此API支援。')
d.fig('9-9','MLP 迴歸：預測與真值散點','越接近對角線越好；還要看高目標值、殘差與單位。教材 RMSE 約 0.53 是該次實驗結果。',note='資料目標以10萬美元為單位。原書文字把比較模型寫classifier可能是筆誤；此處不照抄。')
d.add('用 scikit-learn 建立小型迴歸 MLP','```python\nfrom sklearn.neural_network import MLPRegressor\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\nreg = make_pipeline(StandardScaler(), MLPRegressor(\n    hidden_layer_sizes=(50, 50), early_stopping=True,\n    max_iter=300, random_state=42))\nreg.fit(X_train, y_train)\n```','主教材 Ch.9 pp.300–301；舊稿 06 s.26–27',note='片段假定已有訓練資料；早停預設內部分割，StandardScaler在外層訓練集fit。嚴格比較可另設完全獨立驗證與手動前處理。',cls='small')
d.table('表 9-2：分類的輸出層與損失',['任務','輸出個數','激活','損失'],[['二元','1','Sigmoid','二元交叉熵'],['多標籤','每標籤 1','各自 Sigmoid','各標籤二元交叉熵'],['互斥多類別','每類 1','Softmax','多類別交叉熵']],'主教材 Ch.9 p.304，表 9-2；舊稿 06 s.28–32',note='原表共享隱藏層通常1–5層，此處見上一架構表。二類也能用2輸出softmax，但單輸出sigmoid更直接。')
d.slides[-1]['body']='共通設定：隱藏層通常 1–5 層，依任務調整。\n\n'+d.slides[-1]['body']
d.fig('9-10','分類 MLP：隱藏層 ReLU，輸出層 Softmax','對互斥多類別產生總和為 1 的機率；這些機率仍可能過度自信。')
d.fig('9-11','Fashion MNIST：由像素到服飾類別','每張 28×28 灰階圖可攤成 784 個特徵；10 種類別比單純數字更有外觀變異。')
d.add('訓練損失、驗證分數與測試指標不能混用','- MLPRegressor 的 `score` 是 $R^2$；RMSE 需另算。\n- MLPClassifier 的 `score` 是 accuracy；log loss 另算。\n- `loss_curve_` 記錄最佳化損失，可能包含正則化項。\n- 早停監控的是內部驗證分數，不是最終測試結果。','主教材 Ch.9 pp.301–308',note='此處對照本機sklearn版本；MSE loss的常數尺度及正則化會使loss值不等於RMSE。')
d.add('教材案例提醒：高信心可能仍然答錯','教材 Fashion MNIST 約 90% accuracy 的模型，對不少錯誤仍給出接近 100% 的機率。\n\n檢查錯誤案例與校準；一般框架可考慮 label smoothing。\n\nscikit-learn 的 MLP 不直接提供完整的 label smoothing、dropout 或 TensorBoard 訓練介面。','主教材 Ch.9 pp.307–308；舊稿 06 s.33–38（延伸界線）',note='將label smoothing/dropout/TensorBoard留作後續深度學習框架課，不要求本週安裝框架。',core=False)
d.table('調參次序：先讓模型學得動，再增加容量',['檢查','可調項目','看什麼證據'],[['資料尺度與切分','StandardScaler、資料角色','是否洩漏、分布是否不同'],['最佳化','學習率、batch size、optimizer','收斂曲線、警告、時間'],['容量','隱藏層數、每層神經元','訓練與驗證差距'],['正則化','alpha、早停','是否減少驗證誤差']],'主教材 Ch.9 pp.308–312',note='學習率與batch size互相影響；更大更深不保證較好。不同任務須保留簡單模型基準。')
d.add('深度、寬度與遷移學習','較深網路可重複組合中間特徵，某些函數可比淺層表示更有效率。\n\n過窄的中間層可能形成資訊瓶頸；過多參數則增加訓練與資料需求。\n\n遷移學習重用已有表示；本週先完成小型 MLP，後續再進入 PyTorch 與 GPU。','主教材 Ch.9 pp.308–312',note='萬能近似定理需要適當條件，不能用來保證有限資料、特定訓練算法一定學得好。',core=False)
d.activity('綜合實作：小型 MLP 與簡單模型比較','用已備妥的 digits，小型 MLP `(32,)` 與 `(32,16)` 各跑一次；與標準化 Logistic 比較。\n\n提交：資料切分、accuracy、log loss、訓練時間、兩個錯誤案例。\n\n離線組：10 輸入→50 隱藏→3 輸出的網路，列出各矩陣形狀並計算參數數目。','離線：W1=10×50,b1=50,W2=50×3,b2=3；總703。批次X=m×10，隱藏m×50，輸出m×3。評分在流程、形狀與解釋，不在達到某特定分數。',weight=15)
d.add('離堂檢核：把八週串回同一個學習流程','1. Backprop 計算什麼？Optimizer 改變什麼？\n2. 二元、多類別、多標籤的輸出為何不同？\n3. 為何深度模型仍需與簡單基準比較？\n\n課後：Ch.9 練習 2–9；練習 1 的 playground 與練習 10 大型資料作延伸。',note='答案：梯度／參數；標籤互斥性不同；需要確認額外複雜度有實際泛化收益。',weight=2)
d.finish()
